#!/usr/bin/env bash

set -o errexit
set -o pipefail


readonly src_dir='gutenberg'
readonly virtualenv_dir='virtualenv'


>/dev/null pushd .
cd "$(dirname $(readlink -f $0))"
cd "$(git rev-parse --show-toplevel)"
source "${virtualenv_dir}/bin/activate"

find "${src_dir}" -name '*.py' \
| while read file; do \
    python -m "$(echo ${file%.*} | tr '/' '.')"; \
done

deactivate
> /dev/null popd
